# nixpacks.toml
[packages]
apt = [
    "build-essential", 
    "cmake", 
    "libopenblas-dev", 
    "liblapack-dev", 
    "libjpeg-dev", 
    "libpng-dev", 
    "libboost-dev", 
    "libboost-python-dev",
    "libgtk2.0-dev"
]
